import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Check, ChevronRight, CirclePlus, Flame, LogOut, Pencil, Plus, Target, Trash2, X } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const today = () => new Date().toISOString().slice(0, 10);
const dates = () => Array.from({ length: 7 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - 6 + i); return d; });
const fmt = (d) => d.toLocaleDateString(undefined, { weekday: 'short' });
async function request(path, options = {}, token) { const res = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); const data = res.status === 204 ? null : await res.json().catch(() => ({})); if (!res.ok) throw new Error(data.message || 'Request failed.'); return data; }

function Auth({ onAuth }) { const [mode, setMode] = useState('login'); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { const data = await request(`/auth/${mode === 'login' ? 'login' : 'register'}`, { method: 'POST', body: JSON.stringify(form) }); localStorage.setItem('ritual-auth', JSON.stringify(data)); onAuth(data); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <main className="min-h-screen bg-violet-950 p-5 grid place-items-center"><section className="auth-card"><div className="brand-mark"><Check size={27}/></div><p className="eyebrow">MAKE SPACE FOR WHAT MATTERS</p><h1>Build a life you love.</h1><p className="muted">Small rituals. Remarkable momentum.</p><form onSubmit={submit} className="form">{mode === 'register' && <label>Name<input required minLength="2" maxLength="60" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label>}<label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label>Password<input required type="password" minLength="8" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="At least 8 characters" /></label>{error && <p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Welcome back' : 'Create my account'}<ChevronRight size={18}/></button></form><button className="link-btn" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); }}>{mode === 'login' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button></section></main>;
}
function HabitForm({ habit, onClose, onSave, token }) { const [form, setForm] = useState(habit || { name: '', description: '', color: '#8B5CF6', frequency: 'daily' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { const endpoint = habit ? `/habits/${habit._id}` : '/habits'; const saved = await request(endpoint, { method: habit ? 'PUT' : 'POST', body: JSON.stringify(form) }, token); onSave(saved); onClose(); } catch (err) { setError(err.message); } finally { setBusy(false); } };
return <div className="modal-backdrop" role="presentation"><form className="modal" onSubmit={submit}><div className="modal-head"><h2>{habit ? 'Edit ritual' : 'Create a ritual'}</h2><button type="button" className="icon-button" onClick={onClose}><X/></button></div><label>Ritual name<input autoFocus required maxLength="80" value={form.name} onChange={e => setForm({...form,name:e.target.value})} placeholder="e.g. Read for 20 minutes"/></label><label>A little context <span className="optional">optional</span><textarea maxLength="240" value={form.description} onChange={e => setForm({...form,description:e.target.value})} placeholder="Why does this ritual matter?"/></label><div className="form-row"><label>Frequency<select value={form.frequency} onChange={e => setForm({...form,frequency:e.target.value})}><option value="daily">Every day</option><option value="weekdays">Weekdays</option><option value="weekly">Weekly</option></select></label><label>Color<input className="color" type="color" value={form.color} onChange={e => setForm({...form,color:e.target.value})}/></label></div>{error && <p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Saving…' : habit ? 'Save changes' : 'Create ritual'}</button></form></div> }
function Dashboard({ auth, onLogout }) { const [habits, setHabits] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modal, setModal] = useState(null); const [deleting, setDeleting] = useState(null); const d = today(); const week = dates();
 const load = async () => { setLoading(true); setError(''); try { setHabits(await request('/habits', {}, auth.token)); } catch (e) { setError(e.message); if (/expired|invalid/i.test(e.message)) onLogout(); } finally { setLoading(false); } }; useEffect(() => { load(); }, []);
 const toggle = async (habit) => { try { const updated = await request(`/habits/${habit._id}/toggle`, { method:'PATCH', body: JSON.stringify({ date: d }) }, auth.token); setHabits(habits.map(h => h._id === updated._id ? updated : h)); } catch(e) { setError(e.message); } };
 const save = saved => setHabits(prev => prev.some(h => h._id === saved._id) ? prev.map(h => h._id === saved._id ? saved : h) : [saved, ...prev]);
 const remove = async (id) => { setDeleting(id); try { await request(`/habits/${id}`, { method:'DELETE' }, auth.token); setHabits(habits.filter(h => h._id !== id)); } catch(e) { setError(e.message); } finally { setDeleting(null); } };
 const completed = habits.filter(h => h.completedDates.includes(d)).length; const rate = habits.length ? Math.round(completed / habits.length * 100) : 0;
 return <main className="app-shell"><header><div className="logo"><span className="brand-mark small"><Check size={18}/></span>Ritual</div><div className="account"><span>Hi, {auth.user.name.split(' ')[0]}</span><button className="icon-button" title="Sign out" onClick={onLogout}><LogOut size={19}/></button></div></header><section className="hero"><div><p className="eyebrow">{new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase()}</p><h1>One day at a time.</h1><p>Show up for the person you’re becoming.</p></div><button className="primary create" onClick={() => setModal('new')}><Plus size={19}/>New ritual</button></section>{error && <div className="notice error">{error}<button onClick={() => setError('')}><X size={16}/></button></div>}<section className="stats"><article><Target/><div><strong>{completed}<small> / {habits.length}</small></strong><span>Done today</span></div></article><article><Flame className="orange"/><div><strong>{rate}%</strong><span>Today’s progress</span></div></article></section><section className="content"><div className="section-title"><div><h2>Today’s rituals</h2><p>{habits.length ? `${completed} of ${habits.length} complete — keep going.` : 'Start small. Your first ritual is waiting.'}</p></div></div>{loading ? <div className="state">Loading your rituals…</div> : habits.length === 0 ? <div className="empty"><div className="empty-icon"><CirclePlus/></div><h3>Your ritual space is open</h3><p>Add the first small action you want to make a little more automatic.</p><button className="primary" onClick={() => setModal('new')}>Create your first ritual</button></div> : <div className="habit-list">{habits.map(h => { const isDone = h.completedDates.includes(d); return <article className={`habit ${isDone ? 'done' : ''}`} key={h._id}><button className="check" aria-label={`Mark ${h.name} ${isDone ? 'incomplete' : 'complete'}`} onClick={() => toggle(h)} style={{ '--accent': h.color }}>{isDone && <Check size={18}/>}</button><div className="habit-info"><h3>{h.name}</h3>{h.description && <p>{h.description}</p>}<div className="week">{week.map(day => <span key={day.toISOString()} className={h.completedDates.includes(day.toISOString().slice(0,10)) ? 'week-done' : ''}>{fmt(day).slice(0,1)}</span>)}</div></div><div className="habit-actions"><button className="icon-button" title="Edit ritual" onClick={() => setModal(h)}><Pencil size={17}/></button><button className="icon-button danger" title="Delete ritual" disabled={deleting === h._id} onClick={() => remove(h._id)}><Trash2 size={17}/></button></div></article> })}</div>}</section>{modal && <HabitForm habit={modal === 'new' ? null : modal} token={auth.token} onClose={() => setModal(null)} onSave={save}/>}</main>;
}
function App(){ const [auth,setAuth] = useState(() => { try{return JSON.parse(localStorage.getItem('ritual-auth'))}catch{return null} }); const logout=()=>{localStorage.removeItem('ritual-auth');setAuth(null)}; return auth?.token ? <Dashboard auth={auth} onLogout={logout}/> : <Auth onAuth={setAuth}/> }
createRoot(document.getElementById('root')).render(<App/>);
